### PR TITLE
Switch to kingpin and make scopes configurable

### PR DESCRIPTION
**Pull request by zoni**
This PR re-implements #4 with flag parsing done using kingpin, as requested in https://github.com/kumina/dovecot_exporter/pull/4#issuecomment-339677761.

I've quite deliberately kept the custom string splitting on `,` for `--dovecot.scopes` as I believe it provides a much nicer UI. `--dovecot.scopes="global,user"` makes more sense to me than needing to issue `--dovecot.scope="global" --dovecot.scope="user"`.

(The generated usage documentation for this is also a little easier to understand than the other.)

Individual commit messages provide a little more detail.

### CODE REVIEW

**Comment by zoni** [comment]
PS. As a consequence of this change, flags now require double dashes. `-web.listen-address` becomes `--web.listen-address` for example. I would advise making this explicit in the README or a CHANGES file to warn users.

**Comment by EdSchouten** [comment]
Hey Nick,

Thanks for working on this. This patch looks very reasonable to me. After giving it some more thought, I think I agree with you on the string splitting. Requiring that people pass in multiple flags makes a lot of sense when dealing with strings that may contain arbitrary characters (such as path names), but for the names of these scopes, that's not really important.

@jap, any thoughts on this pull request? Shall I merge this pull request instead of yours?

(P.S.: Wauw. Veel Nederlands hier! ;-) )

**Comment by jap** [comment]
Please go ahead and merge this one!

**Comment by zoni** [comment]
> (P.S.: Wauw. Veel Nederlands hier! ;-) )

We're being sneaky. If you dig further, you'll find @jap and I work at the same company. :wink: I've been doing Go programming for a while (and even contributed to kingpin at some point, so I'm quite familiar with it) so when that came up in #4, I volunteered to do the refactor.

**Comment by EdSchouten** [comment]
Merged. Thanks!

I did change the default scopes back to just `user`. The `global` scope was only added in later versions of Dovecot, apparently.

**Pull request merged**
